extern const GeoLayout nate_Fwalk1[];
extern const GeoLayout nate_Fwalk2[];
extern const GeoLayout nate_Back[];
extern const GeoLayout nate_Bwalk1[];
extern const GeoLayout nate_Bwalk2[];
extern const GeoLayout nate_Left[];
extern const GeoLayout nate_Lwalk1[];
extern const GeoLayout nate_Right[];
extern const GeoLayout nate_Rwalk1[];
extern const GeoLayout nate_geo[];
extern Lights1 nate_Front_lights;
extern Lights1 nate_FrontWalk1_lights;
extern Lights1 nate_FrontWalk2_lights;
extern Lights1 nate_Back_lights;
extern Lights1 nate_BackWalk2_lights;
extern Lights1 nate_BackWalk1_lights;
extern Lights1 nate_Left_lights;
extern Lights1 nate_LeftW_lights;
extern Lights1 nate_Right_lights;
extern Lights1 nate_RightW_lights;
extern u8 nate_overworld_alt1_rgba16[];
extern u8 nate_overworld_alt5_rgba16[];
extern u8 nate_overworld_alt6_rgba16[];
extern u8 nate_overworld_alt3_rgba16[];
extern u8 nate_overworld_alt9_rgba16[];
extern u8 nate_overworld_alt10_rgba16[];
extern u8 nate_overworld_alt2_rgba16[];
extern u8 nate_overworld_alt7_rgba16[];
extern u8 nate_overworld_alt4_rgba16[];
extern u8 nate_overworld_alt11_rgba16[];
extern Vtx nate_NDL_mesh_layer_4_vtx_0[4];
extern Gfx nate_NDL_mesh_layer_4_tri_0[];
extern Vtx nate_fWalk1SwitchOption_fwalk1DL_mesh_layer_4_vtx_0[4];
extern Gfx nate_fWalk1SwitchOption_fwalk1DL_mesh_layer_4_tri_0[];
extern Vtx nate_fWalk2SwitchOption_fwalk2DL_mesh_layer_4_vtx_0[4];
extern Gfx nate_fWalk2SwitchOption_fwalk2DL_mesh_layer_4_tri_0[];
extern Vtx nate_BackSwitchOption_BackDL_mesh_layer_4_vtx_0[4];
extern Gfx nate_BackSwitchOption_BackDL_mesh_layer_4_tri_0[];
extern Vtx nate_bWalk1SwitchOption_bwalk1DL_mesh_layer_4_vtx_0[4];
extern Gfx nate_bWalk1SwitchOption_bwalk1DL_mesh_layer_4_tri_0[];
extern Vtx nate_bWalk2SwitchOption_bwalk2DL_mesh_layer_4_vtx_0[4];
extern Gfx nate_bWalk2SwitchOption_bwalk2DL_mesh_layer_4_tri_0[];
extern Vtx nate_LeftSwitchOption_LeftDL_mesh_layer_4_vtx_0[4];
extern Gfx nate_LeftSwitchOption_LeftDL_mesh_layer_4_tri_0[];
extern Vtx nate_Lwalk1SwitchOption_Lwalk1DL_mesh_layer_4_vtx_0[4];
extern Gfx nate_Lwalk1SwitchOption_Lwalk1DL_mesh_layer_4_tri_0[];
extern Vtx nate_RigthSwitchOption_RigthDL_mesh_layer_4_vtx_0[4];
extern Gfx nate_RigthSwitchOption_RigthDL_mesh_layer_4_tri_0[];
extern Vtx nate_Rwalk1SwitchOption_Rwalk1DL_mesh_layer_4_vtx_0[4];
extern Gfx nate_Rwalk1SwitchOption_Rwalk1DL_mesh_layer_4_tri_0[];
extern Gfx mat_nate_Front[];
extern Gfx mat_revert_nate_Front[];
extern Gfx mat_nate_FrontWalk1[];
extern Gfx mat_revert_nate_FrontWalk1[];
extern Gfx mat_nate_FrontWalk2[];
extern Gfx mat_revert_nate_FrontWalk2[];
extern Gfx mat_nate_Back[];
extern Gfx mat_revert_nate_Back[];
extern Gfx mat_nate_BackWalk2[];
extern Gfx mat_revert_nate_BackWalk2[];
extern Gfx mat_nate_BackWalk1[];
extern Gfx mat_revert_nate_BackWalk1[];
extern Gfx mat_nate_Left[];
extern Gfx mat_revert_nate_Left[];
extern Gfx mat_nate_LeftW[];
extern Gfx mat_revert_nate_LeftW[];
extern Gfx mat_nate_Right[];
extern Gfx mat_revert_nate_Right[];
extern Gfx mat_nate_RightW[];
extern Gfx mat_revert_nate_RightW[];
extern Gfx nate_NDL_mesh_layer_4[];
extern Gfx nate_fWalk1SwitchOption_fwalk1DL_mesh_layer_4[];
extern Gfx nate_fWalk2SwitchOption_fwalk2DL_mesh_layer_4[];
extern Gfx nate_BackSwitchOption_BackDL_mesh_layer_4[];
extern Gfx nate_bWalk1SwitchOption_bwalk1DL_mesh_layer_4[];
extern Gfx nate_bWalk2SwitchOption_bwalk2DL_mesh_layer_4[];
extern Gfx nate_LeftSwitchOption_LeftDL_mesh_layer_4[];
extern Gfx nate_Lwalk1SwitchOption_Lwalk1DL_mesh_layer_4[];
extern Gfx nate_RigthSwitchOption_RigthDL_mesh_layer_4[];
extern Gfx nate_Rwalk1SwitchOption_Rwalk1DL_mesh_layer_4[];
